const data = require('./normalized_data.json');
const persons = data.persons;
console.log('Total persons:', persons.length);
const byGen = {};
persons.forEach(p => { byGen[p.gen] = (byGen[p.gen] || 0) + 1; });
Object.keys(byGen).sort((a, b) => a - b).forEach(g => console.log('  TH' + g + ':', byGen[g]));
const ids = new Set(persons.map(p => p.id));
const broken = persons.filter(p => p.fatherId && !ids.has(p.fatherId));
console.log('Broken fatherId refs:', broken.length);
broken.forEach(b => console.log('  ', b.id, b.name, '->', b.fatherId));
const seen = {};
const dupes = [];
persons.forEach(p => { if (seen[p.id]) dupes.push(p); seen[p.id] = true; });
console.log('Duplicate IDs:', dupes.length);
dupes.forEach(d => console.log('  ', d.id, d.name));
